### PR TITLE
Adds travis.yml for CI testing

### PR DESCRIPTION
**Pull request by jlaura**
Adds a .travis.yml file for CI testing.

### CODE REVIEW

**Comment by jessemapel** [comment]
Is this just a preliminary step for CI? I thought our full test suite is too large to allow for CI right now.

**Comment by jlaura** [comment]
@jessemapel This is an initial stub in.  The test area is currently too large, but this is the first step.  The .travis.yml file also does a nice job demonstrating how to set up an ISIS3 environment without us having to manage all of the third party dependencies within the project.  Unfortunately, the ISIS3 build system is currently hard coded enough that it is not trivial to point to where the externally managed dependencies are being stored (another reason that canonical CMake is such a widely used tool).

**Comment by jlaura** [comment]
@all this is awaiting review - what is the ETA for the review to happen?

**Comment by jessemapel** [comment]
@jlaura We haven't established guidelines for reviewing pull requests outside of our old development routine. It maybe could be done under the current ISIS support work. That decision is up to @scsides.

For this request specifically, It looks good to me and I see no problem with including a stub for Travis CI. I don't know if I have the "authority" to officially "review" this though.

**Pull request closed without merging**
